name = "main-site"
compatibility_date = "2024-02-22"
pages_build_output_dir = "dist"

# To use D1, you must create a database and update the database_id here
# [[d1_databases]]
# binding = "DB"
# database_name = "debug-dimension-db"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
