name = "main-site"
compatibility_date = "2023-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "debug-dimension-db"
database_id = "00000000-0000-0000-0000-000000000000"
